% toolbox\MATLAB_SBML_Structure_Functions\MODEL
%
% Files
%   Model_addCompartment                      - Model_addCompartment 
%   Model_addEvent                            - Model_addEvent 
%   Model_addFunctionDefinition               - Model_addFunctionDefinition 
%   Model_addParameter                        - Model_addParameter 
%   Model_addReaction                         - Model_addReaction 
%   Model_addRule                             - Model_addRule 
%   Model_addSpecies                          - Model_addSpecies 
%   Model_addUnitDefinition                   - Model_addUnitDefinition 
%   Model_create                              - Model_create 
%   Model_createAssignmentRule                - Model_createAssignmentRule 
%   Model_createCompartment                   - Model_createCompartment 
%   Model_createCompartmentVolumeRule         - Model_createCompartmentVolumeRule 
%   Model_createEvent                         - Model_createEvent 
%   Model_createEventAssignment               - Model_createEventAssignment 
%   Model_createFunctionDefinition            - Model_createFunctionDefinition 
%   Model_createKineticLaw                    - Model_createKineticLaw 
%   Model_createKineticLawParameter           - Model_createKineticLawParameter 
%   Model_createModifier                      - Model_createModifier 
%   Model_createParameter                     - Model_createParameter 
%   Model_createParameterRule                 - Model_createParameterRule 
%   Model_createProduct                       - Model_createProduct 
%   Model_createRateRule                      - Model_createRateRule 
%   Model_createReactant                      - Model_createReactant 
%   Model_createReaction                      - Model_createReaction 
%   Model_createSpecies                       - Model_createSpecies 
%   Model_createSpeciesConcentrationRule      - Model_createSpeciesConcentrationRule 
%   Model_createUnit                          - Model_createUnit 
%   Model_createUnitDefinition                - Model_createUnitDefinition 
%   Model_getCompartment                      - Model_getCompartment 
%   Model_getCompartmentById                  - Model_getCompartmentById 
%   Model_getEvent                            - Model_getEvent 
%   Model_getEventById                        - Model_getEventById 
%   Model_getFunctionDefinition               - Model_getFunctionDefinition 
%   Model_getFunctionDefinitionById           - Model_getFunctionDefinitionById 
%   Model_getFunctionIds                      - Model_getFunctionIds 
%   Model_getId                               - Model_getId 
%   Model_getListOfByTypecode                 - Model_getListOfByTypecode 
%   Model_getListOfCompartments               - Model_getListOfCompartments 
%   Model_getListOfEvents                     - Model_getListOfEvents 
%   Model_getListOfFunctionDefinitions        - Model_getListOfFunctionDefinitions 
%   Model_getListOfParameters                 - Model_getListOfParameters 
%   Model_getListOfReactions                  - Model_getListOfReactions 
%   Model_getListOfRules                      - Model_getListOfRules 
%   Model_getListOfSpecies                    - Model_getListOfSpecies 
%   Model_getListOfUnitDefinitions            - Model_getListOfUnitDefinitions 
%   Model_getName                             - Model_getName 
%   Model_getNumCompartments                  - Model_getNumCompartments 
%   Model_getNumEvents                        - Model_getNumEvents 
%   Model_getNumFunctionDefinitions           - Model_getNumFunctionDefinitions
%   Model_getNumParameters                    - Model_getNumParameters 
%   Model_getNumReactions                     - Model_getNumReactions 
%   Model_getNumRules                         - Model_getNumRules 
%   Model_getNumSpecies                       - Model_getNumSpecies 
%   Model_getNumSpeciesWithBoundaryCondition  - Model_getNumSpeciesWithBoundaryCondition 
%   Model_getNumUnitDefinitions               - Model_getNumUnitDefinitions 
%   Model_getParameter                        - Model_getParameter 
%   Model_getParameterById                    - Model_getParameterById 
%   Model_getReaction                         - Model_getReaction 
%   Model_getReactionById                     - Model_getReactionById 
%   Model_getRule                             - Model_getRule 
%   Model_getSpecies                          - Model_getSpecies 
%   Model_getSpeciesById                      - Model_getSpeciesById 
%   Model_getSpeciesNamesAndInitialValues     - Model_getSpeciesNamesAndInitialValues takes a SBMLModel 
%   Model_getUnitDefinition                   - Model_getUnitDefinition 
%   Model_getUnitDefinitionById               - Model_getUnitDefinitionById 
%   Model_isSetId                             - Model_isSetId 
%   Model_isSetName                           - Model_isSetName 
%   Model_moveAllIdsToNames                   - Model_moveAllIdsToNames 
%   Model_moveAllNamesToIds                   - Model_moveAllNamesToIds 
%   Model_moveIdToName                        - Model_moveIdToName 
%   Model_moveNameToId                        - Model_moveNameToId 
%   Model_setId                               - Model_setId 
%   Model_setName                             - Model_setName 
%   Model_unsetId                             - Model_unsetId 
%   Model_unsetName                           - Model_unsetName 
%
%   ADDITIONAL TO libSBML API
%
%   Model_determineRateLawsFromReactions      - Model_determineRateLawsFromReactions  
%   Model_determineRateLawsFromRules          - Model_determineRateLawsFromRules 
%   Model_getAllParameterNamesAndValues       - Model_getAllParameterNamesAndValues 
%   Model_getAllParameterUniqueNamesAndValues - Model_getAllParameterUniqueNamesAndValues 
%   Model_getGlobalParameterNamesAndValues    - Model_getGlobalParameterNamesAndValues 
%   Model_getListOfAlgebraicRules             - Model_getListOfAlgebraicRules
%   Model_getListOfAssignmentRules            - Model_getListOfAssignmentRules 
%   Model_getListOfRateRules                  - Model_getListOfRateRules 
%   Model_getNumAlgebraicRules                - Model_getNumAlgebraicRules 
%   Model_getNumAssignmentRules               - Model_getNumAssignmentRules
%   Model_getNumRateRules                     - Model_getNumRateRules 

